### ISSUE TITLE
Python IO using fiona/OGR

### ISSUE THREAD

**Issue by kylebarron** [geopolars/geopolars#48]
This will be especially performant once https://github.com/Toblerity/Fiona/pull/1121 is merged, using the latest version of OGR

**Comment by kylebarron** [comment]
For now the read io part has been implemented in #95.

We won't write our own bindings to fiona until the arrow data pr has been merged

**Comment by jorisvandenbossche** [comment]
I was planning to comment here, but I see you also just commented about it at https://github.com/Toblerity/Fiona/pull/1121, so you are aware of it.

So you can already get the ArrayStream pointer using "just" the GDAL python API, without the need for fiona or pyogrio (https://github.com/geopandas/pyogrio/pull/155). 
That might be something you could also directly use here? 

Of course to use that, you need to have those Python bindings installed. What fiona or pyogrio give you is a way to install GDAL, since they include GDAL in their wheels, but if you get GDAL that way, you don't have the python bindings (and for this installation use case, you indeed need an API in fiona or pyogrio). But for example if you are using conda and have installed GDAL that way, the python bindings are also installed and can be used.

**Comment by kylebarron** [comment]
Looking at https://github.com/geopandas/pyogrio/pull/155 also makes me think it's wise to let people more knowledgeable on C and GDAL work through the gritty parts 😅
